### ISSUE TITLE
Add summary section to the kube-hunter report component

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard-octant-plugin#27]
Currently the kube-hunter report does not display the summary section as is the case for other report types

![kubehunterreports](https://user-images.githubusercontent.com/1322923/82603198-85d47a00-9bb2-11ea-873e-d2629a8271c2.png)

**Comment by krol3** [comment]
I would like to help :)

**Comment by danielpacak** [comment]
> I would like to help :)

Great! Ping me if you need any help.
