### ISSUE TITLE
Unable to run this on self host k8s cluster on aws ec2 instances

### ISSUE THREAD

**Issue by hsitaa** [aquasecurity/starboard-octant-plugin#46]
1.) setup starboard
2.) get `starboard-octant-plugin` , octant prerequisite done , start octant. it tries to start on browser  [ NOT ON LOCAL so couldn't allow that]
---------------------
Mapped it through proxy , via  ingress to expose it outside of kubernetes cluster 

but UI opens , its unable to access svc, 

getting below message on Top of octant UI:
   Lost connection to Octant service. Retrying

**Comment by danielpacak** [comment]
Hi @hsitaa ! I'm not sure if I understood your setup. Are you able to access the Octant interface after all? Did you check that Octant works without installing the plugin?

**Comment by hsitaa** [comment]
Yes Octant UI works , after installing plugin, able to make that up. and reachable , by mapping the ingress to host and port it is running on. But OCTANT UI doesn't look like have access to k8s cluster it is running on. How to make that feasible

**Comment by danielpacak** [comment]
Sorry @hsitaa , but I don't fully understand your setup. Could you confirm that you're running Octant as a stand-alon application by setting the `KUBECONFIG` environment variable and running the octant binary executable?

**Comment by danielpacak** [comment]
We cannot proceed without additional details. Please reopen if the problem still exists and give the reproduction steps. I was able to run Octant as a desktop app, connect it to the EKS cluster, and display vulnerability reports. Octant relies on the same mechanism as kubectl to connect to the cluster so make sure that this is working.

![octans-aws](https://user-images.githubusercontent.com/1322923/101602190-013a3380-39fe-11eb-9ae0-16fc45cab469.png)
